[
	// A unique identifier that distinguishes this
	// interface from other interfaces.
	uuid(00000001-EAF3-4A7A-A0F2-BCE4C30DA77E),

	// This is version 1.0 of this interface.
	version(1.0)
]
interface AVInterface // The interface is named AVInterface
{
	//A function that takes a zero-terminated string.
	void Output(
	  [in] handle_t hAVInterfaceBinding,
      [in, string] const char* szOutput);
	void Count(
	  [in] handle_t hAVInterfaceBinding,
	  [in] long int iStart,
	  [in] long int iStop);
}